[package]
name = "ferrisprinter"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ferrisprinter_server"
path = "src/bin/server/main.rs"

[dependencies]
actix-web = "4.9.0"
tokio = { version = "1.40.0", features = ["full"] }
